### ISSUE TITLE
cl.exe' failed with exit status 2\n

### ISSUE THREAD

**Issue by Ahmelie** [haidaoxiaofei/mapinference-gis12-upgrade#1]
您好，我在运行skeleton.py文件时出现了如下问题，请问您有什么解决办法吗？
`Traceback (most recent call last):
  File "D:\Downloads\mapinference-gis12-upgrade-master\skeleton.py", line 3, in <module>
    import subiterations
  File "D:\Application\Python\Python27\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
    language_level=self.language_level)
  File "D:\Application\Python\Python27\lib\site-packages\pyximport\pyximport.py", line 233, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "D:\Application\Python\Python27\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "D:\Application\Python\Python27\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "D:\Application\Python\Python27\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "D:\Application\Python\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "D:\Application\Python\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "D:\Application\Python\Python27\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\Application\Python\Python27\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\Application\Python\Python27\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "D:\Application\Python\Python27\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
  File "D:\Application\Python\Python27\lib\distutils\command\build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "D:\Application\Python\Python27\lib\distutils\msvc9compiler.py", line 551, in compile
    raise CompileError(msg)
ImportError: Building module subiterations failed: ["CompileError: command 'D:\\\\Application\\\\Microsoft Visual Studio\\\\2019\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.29.30037\\\\bin\\\\HostX64\\\\x64\\\\cl.exe' failed with exit status 2\n"]`

**Comment by haidaoxiaofei** [comment]
I suggest you to use linux or macos to build the repo. Windows is not easy to use for this repo.
